version: "3"
services:
  jenkins:
    container_name: jenkins
    restart: on-failure
    image: jenkins/jenkins
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./home:/var/jenkins_home

volumes:
  home:

networks:
  jenkins:
    driver: bridge