version: "3"
services:
  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE=MARIADB_DATABASE
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3305:3306"