version: '3'
services:
  mysql:
    container_name: mysql
    restart: always
    image: ubuntu/mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - ./mysql/:/var/lib/mysql
    ports:
      - "3306:3306"
