version: "3"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    expose:
      - 5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
