version: "3"
services:
  sqlserver:
    container_name: sql-server
    restart: always
    image: mcr.microsoft.com/azure-sql-edge
    expose:
      - 1433
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD
    volumes:
      - ./sqlserver:/var/opt/mssql
    ports:
      - "1433:1433"
